/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Cascadia Code', 'Fira Code', 'monospace'],
        // Customer-facing redesign typefaces (design/premium_fast_casual_digital_menu/DESIGN.md)
        jakarta: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        work: ['Work Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50:  '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        surface: {
          DEFAULT: '#ffffff',
          raised: '#fafafa',
          overlay: '#f4f4f5',
        },
        // ── Customer redesign tokens (`cust-*`) ──────────────────────────────
        // Namespaced so they never collide with the admin/POS/KDS `primary`/`surface`
        // scales above. Values come straight from
        // design/premium_fast_casual_digital_menu/DESIGN.md.
        'cust-primary': '#a73a00',
        'cust-on-primary': '#ffffff',
        'cust-primary-container': '#ff5c00',
        'cust-on-primary-container': '#521800',
        'cust-primary-fixed': '#ffdbce',
        'cust-primary-fixed-dim': '#ffb59a',
        'cust-on-primary-fixed': '#370e00',
        'cust-on-primary-fixed-variant': '#802a00',
        'cust-inverse-primary': '#ffb59a',
        'cust-secondary': '#5f5e5e',
        'cust-on-secondary': '#ffffff',
        'cust-secondary-container': '#e5e2e1',
        'cust-on-secondary-container': '#656464',
        'cust-secondary-fixed': '#e5e2e1',
        'cust-secondary-fixed-dim': '#c8c6c5',
        'cust-on-secondary-fixed': '#1c1b1b',
        'cust-on-secondary-fixed-variant': '#474646',
        'cust-tertiary': '#5d5f5f',
        'cust-on-tertiary': '#ffffff',
        'cust-tertiary-container': '#929393',
        'cust-on-tertiary-container': '#2a2c2c',
        'cust-error': '#ba1a1a',
        'cust-on-error': '#ffffff',
        'cust-error-container': '#ffdad6',
        'cust-on-error-container': '#93000a',
        'cust-surface': '#fbf9f9',
        'cust-surface-dim': '#dbdad9',
        'cust-surface-bright': '#fbf9f9',
        'cust-surface-container-lowest': '#ffffff',
        'cust-surface-container-low': '#f5f3f3',
        'cust-surface-container': '#efeded',
        'cust-surface-container-high': '#e9e8e7',
        'cust-surface-container-highest': '#e3e2e2',
        'cust-surface-variant': '#e3e2e2',
        'cust-on-surface': '#1b1c1c',
        'cust-on-surface-variant': '#5b4137',
        'cust-inverse-surface': '#303031',
        'cust-inverse-on-surface': '#f2f0f0',
        'cust-outline': '#8f7065',
        'cust-outline-variant': '#e4beb1',
        'cust-background': '#fbf9f9',
        'cust-on-background': '#1b1c1c',
      },
      boxShadow: {
        'xs':     '0 1px 2px rgba(0,0,0,0.05)',
        'sm':     '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card':   '0 1px 4px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'md':     '0 4px 8px rgba(0,0,0,0.06), 0 2px 4px rgba(0,0,0,0.04)',
        'lg':     '0 8px 20px rgba(0,0,0,0.07), 0 4px 8px rgba(0,0,0,0.04)',
        'xl':     '0 16px 32px rgba(0,0,0,0.08), 0 8px 16px rgba(0,0,0,0.04)',
        'modal':  '0 24px 56px rgba(0,0,0,0.14), 0 8px 24px rgba(0,0,0,0.08)',
        'ring':         '0 0 0 3px rgba(234,88,12,0.14)',
        'ring-blue':    '0 0 0 3px rgba(37,99,235,0.14)',
        'ring-green':   '0 0 0 3px rgba(22,163,74,0.14)',
        'ring-red':     '0 0 0 3px rgba(220,38,38,0.14)',
        'ring-inset':   'inset 0 0 0 2px rgba(234,88,12,0.20)',
        'sidebar':      '4px 0 24px rgba(0,0,0,0.12)',
        // Customer redesign elevation scale
        'cust-card':    '0px 4px 20px rgba(0,0,0,0.06)',
        'cust-banner':  '0px 4px 20px rgba(0,0,0,0.1)',
        'cust-modal':   '0px 10px 30px rgba(0,0,0,0.15)',
        'cust-nav':     '0px -4px 20px rgba(0,0,0,0.15)',
      },
      borderRadius: {
        'xs':  '3px',
        'sm':  '5px',
        DEFAULT: '7px',
        'md':  '9px',
        'lg':  '11px',
        'xl':  '14px',
        '2xl': '18px',
        '3xl': '24px',
      },
      spacing: {
        '4.5': '1.125rem',
        '13':  '3.25rem',
        '15':  '3.75rem',
        '18':  '4.5rem',
      },
      fontSize: {
        'xxs': ['10px', { lineHeight: '14px' }],
        'xs':  ['12px', { lineHeight: '18px' }],
        'sm':  ['13px', { lineHeight: '20px' }],
        'base':['14px', { lineHeight: '22px' }],
        'md':  ['15px', { lineHeight: '24px' }],
        'lg':  ['16px', { lineHeight: '26px' }],
        'xl':  ['18px', { lineHeight: '28px' }],
        '2xl': ['22px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
      },
      animation: {
        'fade-in':       'fadeIn 0.18s ease-out',
        'fade-in-up':    'fadeInUp 0.22s ease-out',
        'scale-in':      'scaleIn 0.15s ease-out',
        'slide-in-left': 'slideInLeft 0.22s ease-out',
        'spin-slow':     'spin 2s linear infinite',
        'pulse-soft':    'pulseSoft 2.4s ease-in-out infinite',
        'shimmer':       'shimmer 1.8s linear infinite',
        'bounce-soft':   'bounceSoft 0.5s cubic-bezier(0.36,0.07,0.19,0.97)',
      },
      keyframes: {
        fadeIn:      { from: { opacity: '0' },                                   to: { opacity: '1' } },
        fadeInUp:    { from: { opacity: '0', transform: 'translateY(8px)' },     to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:     { from: { opacity: '0', transform: 'scale(0.96)' },         to: { opacity: '1', transform: 'scale(1)' } },
        slideInLeft: { from: { opacity: '0', transform: 'translateX(-10px)' },   to: { opacity: '1', transform: 'translateX(0)' } },
        pulseSoft:   { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.55' } },
        bounceSoft:  { '0%,100%': { transform: 'translateY(0)' }, '40%': { transform: 'translateY(-6px)' }, '60%': { transform: 'translateY(-3px)' } },
        shimmer:     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34,1.56,0.64,1)',
        'ease-out-back': 'cubic-bezier(0.34,1.56,0.64,1)',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [],
};
